# Assignment 2

Name: Aziz Sayyad
Roll: 381069
PRN: 22420090
Batch: A3

#### Perform bag-of-words approach (count occurrence, normalized count occurrence), TF-IDF on data. Create embeddings using Word2Vec

In [1]:
!pip install nltk gensim scikit-learn

In [2]:
#imports
import nltk
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from gensim.models import Word2Vec

nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Aziz\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [3]:
# sample dataset

documents = [
    "NLP is a fascinating field of AI",
    "AI and NLP are transforming the world",
    "Machine learning is part of AI",
    "We are learning NLP using Python"
]

print(documents)


['NLP is a fascinating field of AI', 'AI and NLP are transforming the world', 'Machine learning is part of AI', 'We are learning NLP using Python']


In [4]:
#Bag-of-Words (Count Occurrence)

count_vectorizer = CountVectorizer()
bow_counts = count_vectorizer.fit_transform(documents)

print("Vocabulary:")
print(count_vectorizer.get_feature_names_out())

print("\nBag-of-Words (Count Occurrence):")
print(bow_counts.toarray())

Vocabulary:
['ai' 'and' 'are' 'fascinating' 'field' 'is' 'learning' 'machine' 'nlp'
 'of' 'part' 'python' 'the' 'transforming' 'using' 'we' 'world']

Bag-of-Words (Count Occurrence):
[[1 0 0 1 1 1 0 0 1 1 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 1 0 0 0 1 1 0 0 1]
 [1 0 0 0 0 1 1 1 0 1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 1 0 0 1 0 0 1 1 0]]


In [5]:
# Bag-of-Words (Normalized Count Occurrence) (L2 Normalization)
from sklearn.preprocessing import normalize

count_vectorizer_norm = CountVectorizer()
bow_counts = count_vectorizer_norm.fit_transform(documents)
bow_normalized = normalize(bow_counts, norm='l2', axis=1)

print("Vocabulary:")
print(count_vectorizer_norm.get_feature_names_out())

print("\nNormalized Bag-of-Words (L2 Normalization):")
print(bow_normalized.toarray())

Vocabulary:
['ai' 'and' 'are' 'fascinating' 'field' 'is' 'learning' 'machine' 'nlp'
 'of' 'part' 'python' 'the' 'transforming' 'using' 'we' 'world']

Normalized Bag-of-Words (L2 Normalization):
[[0.40824829 0.         0.         0.40824829 0.40824829 0.40824829
  0.         0.         0.40824829 0.40824829 0.         0.
  0.         0.         0.         0.         0.        ]
 [0.37796447 0.37796447 0.37796447 0.         0.         0.
  0.         0.         0.37796447 0.         0.         0.
  0.37796447 0.37796447 0.         0.         0.37796447]
 [0.40824829 0.         0.         0.         0.         0.40824829
  0.40824829 0.40824829 0.         0.40824829 0.40824829 0.
  0.         0.         0.         0.         0.        ]
 [0.         0.         0.40824829 0.         0.         0.
  0.40824829 0.         0.40824829 0.         0.         0.40824829
  0.         0.         0.40824829 0.40824829 0.        ]]


In [6]:
# TF-IDF Representation
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(documents)

print("Vocabulary:")
print(tfidf_vectorizer.get_feature_names_out())

print("\nTF-IDF Matrix:")
print(tfidf_matrix.toarray())


Vocabulary:
['ai' 'and' 'are' 'fascinating' 'field' 'is' 'learning' 'machine' 'nlp'
 'of' 'part' 'python' 'the' 'transforming' 'using' 'we' 'world']

TF-IDF Matrix:
[[0.31685436 0.         0.         0.49641358 0.49641358 0.39137817
  0.         0.         0.31685436 0.39137817 0.         0.
  0.         0.         0.         0.         0.        ]
 [0.27375357 0.42888787 0.33814012 0.         0.         0.
  0.         0.         0.27375357 0.         0.         0.
  0.42888787 0.42888787 0.         0.         0.42888787]
 [0.30880963 0.         0.         0.         0.         0.38144133
  0.38144133 0.48380996 0.         0.38144133 0.48380996 0.
  0.         0.         0.         0.         0.        ]
 [0.         0.         0.36559366 0.         0.         0.
  0.36559366 0.         0.29597957 0.         0.         0.46370919
  0.         0.         0.46370919 0.46370919 0.        ]]


In [8]:
# Tokenize Sentences for Word2Vec
from nltk.tokenize import word_tokenize
import nltk

nltk.download('punkt_tab')
tokenized_docs = [word_tokenize(doc.lower()) for doc in documents]
print(tokenized_docs)

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Aziz\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.


[['nlp', 'is', 'a', 'fascinating', 'field', 'of', 'ai'], ['ai', 'and', 'nlp', 'are', 'transforming', 'the', 'world'], ['machine', 'learning', 'is', 'part', 'of', 'ai'], ['we', 'are', 'learning', 'nlp', 'using', 'python']]


In [13]:
# Train Word2Vec Model
w2v_model = Word2Vec(
    sentences=tokenized_docs,
    vector_size=100,
    window=5,
    min_count=1,
    workers=4
)

In [14]:
# Word Embeddings (Vector Representation)
print("Vector for word 'nlp':")
print(w2v_model.wv['nlp'])

print("\nVector size:", w2v_model.wv.vector_size)

Vector for word 'nlp':
[-5.3624751e-04  2.3595389e-04  5.1066712e-03  9.0118591e-03
 -9.3011241e-03 -7.1189855e-03  6.4629051e-03  8.9754611e-03
 -5.0167316e-03 -3.7696774e-03  7.3830173e-03 -1.5340926e-03
 -4.5374897e-03  6.5556653e-03 -4.8580295e-03 -1.8119088e-03
  2.8823533e-03  9.9294621e-04 -8.2899714e-03 -9.4528217e-03
  7.3149633e-03  5.0686072e-03  6.7640329e-03  7.5895624e-04
  6.3553732e-03 -3.4039100e-03 -9.4818178e-04  5.7695014e-03
 -7.5245644e-03 -3.9308621e-03 -7.5086360e-03 -9.2933915e-04
  9.5387958e-03 -7.3262951e-03 -2.3315044e-03 -1.9397329e-03
  8.0782799e-03 -5.9279017e-03  5.0355458e-05 -4.7538439e-03
 -9.6039902e-03  5.0068884e-03 -8.7626893e-03 -4.3947552e-03
 -3.6295416e-05 -2.9653395e-04 -7.6591391e-03  9.6185701e-03
  4.9841879e-03  9.2386482e-03 -8.1562735e-03  4.4941148e-03
 -4.1396795e-03  8.2242518e-04  8.5001420e-03 -4.4606607e-03
  4.5180363e-03 -6.7847786e-03 -3.5522149e-03  9.4017386e-03
 -1.5806501e-03  3.2338084e-04 -4.1420711e-03 -7.6840390e-03
 

In [15]:
#Similar Words using Word2Vec
similar_words = w2v_model.wv.most_similar('ai')
print("Words similar to 'ai':")
print(similar_words)


Words similar to 'ai':
[('fascinating', 0.16072483360767365), ('field', 0.13748566806316376), ('a', 0.12290510535240173), ('python', 0.0854606181383133), ('of', 0.06797593832015991), ('the', 0.033640582114458084), ('we', 0.022077448666095734), ('learning', 0.009391166269779205), ('and', 0.008315932005643845), ('are', 0.0042861527763307095)]
